services:
  db:
    build:
      context: .
      dockerfile: ./.runtime_do_not_edit/docker/Dockerfile.takserver-db
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - "./.data/db:/var/lib/postgresql/data:z"
      - "./.runtime_do_not_edit/tak:/opt/tak:z"
    networks:
      tak:
        aliases:
          - tak-database
    restart: unless-stopped
    
  tak:
    build:
      context: .
      dockerfile: ./.runtime_do_not_edit/docker/Dockerfile.takserver
    volumes:
      - "./.runtime_do_not_edit/tak:/opt/tak:z"
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    ports:
      - "8443:8443"
      - "8444:8444"
      - "8446:8446"
      - "8089:8089"
      - "9000:9000"
      - "9001:9001"
    networks:
      tak:
    depends_on:
      - db
    restart: unless-stopped
networks:
  tak:
